accounts/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    email = models.EmailField(unique=True)


# class FriendShip(models.Model):

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import SignUpForm


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("index")

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}signup{% endblock %}

{% block content %}
<div>
  <h2>ユーザー登録</h2>
  <div>
    <form method="post">
      {{ form }}
      {% csrf_token %}
      <button type="submit">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <a href="{% url 'accounts:signup' %}">signup</a>
  {% block content %}{% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}